# Generated by Django 5.2.4 on 2025-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="location",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
