# Generated by Django 5.2.4 on 2025-08-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_customuser_profile_picture_postt_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="postt",
            name="username",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
