# Generated by Django 5.2.4 on 2025-08-28 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
